#!/usr/bin/env python3
"""Set or update a secret in .secrets/api-keys.env.

Usage:
    python3 scripts/set_secret.py OPENROUTER_API_KEY <value>
    python3 scripts/set_secret.py GITHUB_TOKEN <value>
"""

import os
import pathlib
import sys

SCRIPT_DIR = pathlib.Path(__file__).parent
SECRETS_FILE = SCRIPT_DIR.parent / ".secrets" / "api-keys.env"
WRAPPER = SCRIPT_DIR.parent / ".secrets" / "source-secrets.sh"
EXAMPLE_FILE = SCRIPT_DIR.parent / "api-keys.env.example"


def load_env(path: pathlib.Path) -> dict[str, str]:
    env = {}
    if path.exists():
        for line in path.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, val = line.partition("=")
                env[key.strip()] = val.strip().strip("'\"").strip()
    return env


def save_env(path: pathlib.Path, env: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [f"# Secrets — DO NOT commit to Git\n"]
    for key in sorted(env):
        val = env[key]
        if val:
            lines.append(f'{key}="{val}"\n')
        else:
            lines.append(f"# {key}=...\n")
    path.write_text("".join(lines))
    path.chmod(0o600)


def main() -> int:
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} KEY VALUE", file=sys.stderr)
        return 1

    key = sys.argv[1].upper()
    value = sys.argv[2].strip()

    # Validate key name
    VALID_KEYS = {"GITHUB_TOKEN", "OPENROUTER_API_KEY", "ANTHROPIC_API_KEY"}
    if key not in VALID_KEYS:
        print(f"Unknown key: {key}. Valid: {', '.join(sorted(VALID_KEYS))}", file=sys.stderr)
        return 1

    if not EXAMPLE_FILE.exists():
        EXAMPLE_FILE.write_text(
            "# Secrets für das Smart-Home-Repo\n"
            "# Diese Datei wird NICHT ins Git-Repo übernommen.\n\n"
            "# GitHub / Push\n"
            "# GITHUB_TOKEN=ghp_...\n\n"
            "# OpenRouter API Key\n"
            "# OPENROUTER_API_KEY=sk-or-...\n"
        )
        EXAMPLE_FILE.chmod(0o644)

    env = load_env(SECRETS_FILE)
    env[key] = value
    save_env(SECRETS_FILE, env)

    # Generate source wrapper
    WRAPPER.parent.mkdir(parents=True, exist_ok=True)
    WRAPPER.write_text(
        f"#!/bin/bash\n"
        f"# Autogenerated. Source this to load secrets:\n"
        f'#   source "{WRAPPER.relative_to(WRAPPER.parent)}"\n'
        f"export {key}=\"{value}\"\n"
    )
    WRAPPER.chmod(0o600)

    print(f"✅ {key} gespeichert in {SECRETS_FILE}")
    print(f"   Wrapper: {WRAPPER}")
    print(f'   Einmalig laden: source "{WRAPPER}"')
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
